name: 'Package aws-durable-lambda plugin'

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]

jobs:
  package:
    # Don't build if Semantic Release pushes a ci skip commit
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    
    strategy:
      matrix:
        bundler: [vanilla, serverless-esbuild, serverless-jetpack, serverless-plugin-typescript, serverless-webpack]
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/fermium

      # TODO: Can we build/test the plugin once and then share with the example project jobs?
      - run: yarn install
        name: Install plugin dependencies
        working-directory: plugin
      - run: yarn build
        name: Build plugin
        working-directory: plugin

      - run: yarn install
        name: Install example project dependencies
        working-directory: examples/${{ matrix.bundler }}
      - run: yarn sls package --stage sandbox --verbose
        name: Package example project
        working-directory: examples/${{ matrix.bundler }}
      # TODO: We need to verify the output (or deploy it somewhere and fire and API call)
      # Otherwise only the most obvious errors will show up